# 加速器相关配置
project_dir: ./checkpoints/uno_grpo_vlm/single_syncd_1w_grpo_eta3_lr5e5_lora512
mixed_precision: "bf16"  # 可选值: "no", "fp16", "bf16"
gradient_accumulation_steps: 4
seed: 42
wandb_project_name: "uno_syncd_grpo_1w_vlm"
wandb_run_name: null # null为随机
wandb_tags: [ 'rank512', 'lr5e5', 'bs1', 'Syncd1w', '512x512', 'sample_step_25', 'concep + following_cot', '0.5 + 0.5', 'N_Gen_12', 'eta3']

# 模型相关配置
model_name: "flux-dev-uno-fused"  # 可选值: "flux-dev", "flux-schnell", "flux-dev-uno-fused"
load_pretrain_lora: true
lora_rank: 512
double_blocks_indices: null  # null 表示应用到所有 double blocks
single_blocks_indices: null  # null 表示应用到所有 single blocks
pe: "d"  # 可选值: "d", "h", "w", "o"
gradient_checkpoint: true
ema: false
ema_interval: 1
ema_decay: 0.99
selective_checkpointing: 1.0

# grpo specific 
fsdp_sharding_startegy: full
sampling_steps: 25 
eta: 0.3
sde_solver: true 
shift: 3 # SD3时间步偏移参数 
guidance_scale: 3.5 # 图像生成时的引导尺度(待定)
init_same_noise: true # 是否对每个生成批次使用相同的初始噪声 
text_dropout: 0.0
use_clip: true
use_dino: true
clip_weight: 0.5
dino_weight: 0.5
task_concept: concept
task_following: text_cot

clip_range: 1e-4 # PPO 裁剪范围 (epsilon)
adv_clip_max: 5.0 # 优势值的裁剪最大值

use_group: true # 是否在每个批次内生成多张图像并组内标准化奖励
num_generations: 12 # 每个提示生成多少张图像 (当use_group为True时)
timestep_fraction: 0.6 # 训练每个轨迹时，使用多少比例的时间步进行PPO更新    

# 优化器配置
learning_rate: 5.0e-5
adam_betas: [ 0.9, 0.999 ]
adam_eps: 1.0e-8
adam_weight_decay: 0.00011
max_grad_norm: 1.0

# 学习率调度器配置
lr_scheduler: "constant_with_warmup"
lr_warmup_steps: 0
max_train_steps: 100000
lr_num_cycles: 1

text_dropout: 0
w: 512
h: 512

# 其他配置
resume_from_checkpoint: null  # 可选值: null, "latest", 或者具体的检查点路径
gradient_checkpointing: true

## dataloader
# TODO: change to your own dataset, or use one data syenthsize pipeline comming in the future. stay tuned
# train_data_json: ./datasets/syncd_meta/train_1w_cleaned.json
train_data_json: ./datasets/syncd_meta/train_1w_prompt_embedding.json
train_batch_size: 1
train_image_base: ./datasets/syncd
resolution: 512
resolution_ref: 512
sampler_seed: 1223627
dataloader_num_workers: 4
lr_power: 1.0

## misc
resume_from_checkpoint: null
checkpointing_steps: 50

# other pa
sp_size: 1
train_sp_batch_size: 1
use_cpu_offload: false
master_weight_type: fp32
