eval_json_path: ./datasets/dreambench_singleip.json
offload: false
num_images_per_prompt: 1
model_type: flux-dev
width: 512
height: 512
ref_size: -1
num_steps: 25
guidance: 4
seed: 3407
save_path: ./datasets/dreambooth/uno_sft/
only_lora: true
concat_refs: False
lora_rank: 512
data_resolution: 512
pe: d
lora_path: ./checkpoints/


